export const MOVEMENT_REPOSITORY = Symbol('MOVEMENT_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const WAREHOUSE_REPOSITORY = Symbol('WAREHOUSE_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
